name: PlayerOutline
main: us.ignismc.playeroutline.PlayerOutline
version: 0.0.1
depend:
  - Stats
commands:
  profile:
    description:  Show profile
    usage:  /profile
    permission: playeroutline.profile
    permission-message: You don't have profile permissions
    
permissions:
  playeroutline.profile:
    description:  access to the basic profile command
    default: true
      
  playeroutline.*:
    description: Gives permission for all playeroutline commands
    children:
      playeroutline.show.*: true
      playeroutline.bio.*: true
      
  playeroutline.show.*:
    description: Gives permission to show profiles
    children: 
      playeroutline.show.self: true
      playeroutline.show.others: true
  playeroutline.show.self:
    description: Gives permission to show your own profile
    default: true
  playeroutline.show.others:
    description: Gives permission to show others profiles
    default: true

  playeroutline.bio.*:
    description: Gives permission to show profiles
    children: 
      playeroutline.bio.self: true
      playeroutline.bio.others: true
  playeroutline.bio.self:
    description: Gives permission to edit your own bio
    default: true
  playeroutline.bio.others:
    description: Gives permission to edit others bios
    default: false